name: bimo_is_true
description: Projeto para disciplina de Interface Homem-Maquina (IHM) e Deselvoldimento para dispositivos moveis (MOBILE)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.1.0
  flame: any
  tiled: any
  http: ^0.12.0+2
  sqflite: any
  audioplayers: 0.13.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter:
  fonts:
    - family: Special
      fonts:
        - asset: assets/fonts/SpecialElite.ttf

  uses-material-design: true
  assets:
    - assets/images/icons/iniciar.png
    - assets/images/icons/config.png
    - assets/images/icons/ajuda.png
    - assets/images/icons/info.png
    - assets/images/icons/sair.png
    - assets/images/icons/voltar.png
    - assets/images/icons/home.png
    - assets/images/icons/salvar.png
    - assets/images/icons/musicaOn.png
    - assets/images/icons/musicaOff.png
    - assets/images/icons/baixo.png
    - assets/images/icons/cima.png
    - assets/images/icons/direita.png
    - assets/images/icons/esquerda.png
    - assets/images/icons/inform.png
    - assets/images/icons/mais.png
    - assets/images/icons/menos.png
    - assets/images/icons/confirmar.png
    - assets/images/icons/cancelar.png
    - assets/images/icons/parar.png
    - assets/images/icons/pausar.png
    - assets/images/icons/porta.png
    - assets/images/icons/velocidade.png
    - assets/images/icons/audioOn.png
    - assets/images/icons/audioOff.png
    - assets/images/icons/estrela.png
    - assets/images/icons/bloqueado.png
    - assets/images/icons/livre.png
    - assets/images/icons/atencao.png
    - assets/images/icons/pessoa.png
    - assets/images/icons/segurar.png
    - assets/images/icons/soltar.png
    - assets/icon.png
    - assets/back.png
    - assets/back_logo.png
    - assets/logo bimo.png
    - assets/tiles/mapa.tmx
    - assets/images/blocos.png
    - assets/images/bloco.png
    - assets/images/blockx64.png
    - assets/tiles/map0.tmx
    - assets/tiles/map1.tmx
    - assets/tiles/map2.tmx
    - assets/tiles/map3.tmx
    - assets/tiles/map4.tmx
    - assets/images/joystick_background.png
    - assets/images/joystick_knob.png
    - assets/images/sprite/play_0.png
    - assets/images/sprite/play_1.png
    - assets/images/sprite/play_2.png
    - assets/images/sprite/play_3.png
    - assets/images/sprite/play_4.png
    - assets/images/sprite/play_5.png
    - assets/audio/sakura.mp3
    - assets/audio/iniciofase.ogg
    - assets/audio/andando.ogg

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon.png"
