name: tableblocktrue
description: Projeto para disciplina de Interface Homem-Maquina (IHM) e Deselvoldimento para dispositivos moveis (MOBILE)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.1.0
  flame: ^0.15.2
  tiled: ^0.2.1
  tiler: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter:
  fonts:
    - family: Special
      fonts:
        - asset: assets/fonts/SpecialElite.ttf

  uses-material-design: true
  assets:
    - assets/icons/iniciar.png
    - assets/icons/config.png
    - assets/icons/ajuda.png
    - assets/icons/info.png
    - assets/icons/sair.png
    - assets/icons/voltar.png
    - assets/icons/home.png
    - assets/icons/salvar.png
    - assets/icons/musicaOn.png
    - assets/icons/musicaOff.png
    - assets/icons/baixo.png
    - assets/icons/cima.png
    - assets/icons/direita.png
    - assets/icons/esquerda.png
    - assets/icons/inform.png
    - assets/icons/mais.png
    - assets/icons/menos.png
    - assets/icons/confirmar.png
    - assets/icons/cancelar.png
    - assets/icons/parar.png
    - assets/icons/pausar.png
    - assets/icons/porta.png
    - assets/icons/velocidade.png
    - assets/icons/audioOn.png
    - assets/icons/audioOff.png
    - assets/icon.png
    - assets/fundo.jpg
    - assets/images/sprite/bege_padrao.png
    - assets/images/sprite/bege_direita1.png
    - assets/images/sprite/bege_direita2.png
    - assets/images/sprite/tileset.png
    - assets/images/mapa.png
    - assets/tiles/mapa.json
    - assets/tiles/mapa.tmx
    - assets/tiles/mapa2.tmx
    - assets/tiles/tileset.tsx

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon.png"
