name: log_man
description: Projeto para disciplina de Interface Homem-Maquina (IHM) e Deselvoldimento para dispositivos moveis (MOBILE)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.1.0
  flame: ^0.15.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/iniciar.png
    - assets/icons/config.png
    - assets/icons/ajuda.png
    - assets/icons/info.png
    - assets/icons/sair.png
    - assets/icon.png

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon.png"
